language: python
branches:
  only:
    - master
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - make check
  - PYTHONPATH="." py.test --cov .
after_success:
  - coveralls
